<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('permissions')->insert([
            [
                'id' => 1,
                'name' => 'Super Admin',
                'key' => 'super-admin',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Admin',
                'key' => 'admin',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Get All Restaurant',
                'key' => 'get-all-restaurant',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Get One Restaurant',
                'key' => 'get-one-restaurant',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Update Restaurant',
                'key' => 'update-restaurant',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Delete Restaurant',
                'key' => 'delete-restaurant',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Get One Table',
                'key' => 'get-one-table',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Get All Table by Restaurant ID',
                'key' => 'get-all-table-by-restaurant-id',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Add Table',
                'key' => 'add-table',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Update Table',
                'key' => 'update-table',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Delete Table',
                'key' => 'delete-table',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Get One Food',
                'key' => 'get-one-food',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'Get All Food by Restaurant ID',
                'key' => 'get-all-food-by-restaurant-id',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Add Food',
                'key' => 'add-food',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'Update Food',
                'key' => 'update-food',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Delete Food',
                'key' => 'delete-food',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'Get One Transaction',
                'key' => 'get-one-transaction',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Get One Transaction on Table ID',
                'key' => 'get-one-transaction-on-table-id',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'Get All Transaction by Restaurant ID',
                'key' => 'get-all-transaction-by-restaurant-id',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'Add Transaction',
                'key' => 'add-transaction',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'name' => 'Payment',
                'key' => 'payment',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Undo Payment',
                'key' => 'undo-payment',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'Delete Transaction',
                'key' => 'delete-transaction',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'Get One Order',
                'key' => 'get-one-order',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' => 'Get All Order by Restaurant ID',
                'key' => 'get-all-order-by-restaurant-id',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'Get All Order by Transaction ID',
                'key' => 'get-all-order-by-transaction-id',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'Add Order',
                'key' => 'add-order',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'name' => 'Update Order',
                'key' => 'update-order',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'name' => 'Delete Order',
                'key' => 'delete-order',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'Get All Restaurant by Admin',
                'key' => 'get-all-restaurant-by-admin',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
