<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('role_permissions')->insert([
            [
                'id' => 1,
                'role_id' => 1,
                'permission_id' => 1,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'role_id' => 2,
                'permission_id' => 2,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'role_id' => 2,
                'permission_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'role_id' => 2,
                'permission_id' => 5,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'role_id' => 2,
                'permission_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'role_id' => 2,
                'permission_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'role_id' => 2,
                'permission_id' => 9,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'role_id' => 2,
                'permission_id' => 10,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'role_id' => 2,
                'permission_id' => 11,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'role_id' => 2,
                'permission_id' => 12,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'role_id' => 2,
                'permission_id' => 13,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'role_id' => 2,
                'permission_id' => 14,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'role_id' => 2,
                'permission_id' => 15,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'role_id' => 2,
                'permission_id' => 16,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'role_id' => 2,
                'permission_id' => 17,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'role_id' => 2,
                'permission_id' => 18,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'role_id' => 2,
                'permission_id' => 19,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'role_id' => 2,
                'permission_id' => 20,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'role_id' => 2,
                'permission_id' => 21,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'role_id' => 2,
                'permission_id' => 22,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'role_id' => 2,
                'permission_id' => 23,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'role_id' => 2,
                'permission_id' => 24,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'role_id' => 2,
                'permission_id' => 25,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'role_id' => 2,
                'permission_id' => 26,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'role_id' => 2,
                'permission_id' => 27,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'role_id' => 2,
                'permission_id' => 28,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'role_id' => 2,
                'permission_id' => 29,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'role_id' => 3,
                'permission_id' => 4,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'role_id' => 3,
                'permission_id' => 7,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'role_id' => 3,
                'permission_id' => 8,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'role_id' => 3,
                'permission_id' => 10,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'role_id' => 3,
                'permission_id' => 12,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'role_id' => 3,
                'permission_id' => 13,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'role_id' => 3,
                'permission_id' => 17,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'role_id' => 3,
                'permission_id' => 18,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'role_id' => 3,
                'permission_id' => 19,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'role_id' => 3,
                'permission_id' => 20,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'role_id' => 3,
                'permission_id' => 21,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'role_id' => 3,
                'permission_id' => 22,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'role_id' => 3,
                'permission_id' => 23,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'role_id' => 3,
                'permission_id' => 24,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'role_id' => 3,
                'permission_id' => 26,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'role_id' => 3,
                'permission_id' => 27,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'role_id' => 3,
                'permission_id' => 28,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'role_id' => 3,
                'permission_id' => 29,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'role_id' => 4,
                'permission_id' => 12,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'role_id' => 4,
                'permission_id' => 13,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'role_id' => 4,
                'permission_id' => 18,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'role_id' => 4,
                'permission_id' => 27,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'role_id' => 4,
                'permission_id' => 26,
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
